### ISSUE TITLE
Modules test sometimes time out on Windows

### ISSUE THREAD

**Issue by dhaavi** [safing/portbase#66]
Sometimes the module tests fail - see https://travis-ci.org/github/safing/portbase/jobs/706840823.

Failing test:

```
[ FAIL ] go test -cover -short github.com/safing/portbase/modules
taking too long

goroutine 22 [running]:
runtime/pprof.writeGoroutineStacks(0x5eb3a0, 0xc0000bc010, 0x30, 0xd0)
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/runtime/pprof/pprof.go:665 +0xa4
runtime/pprof.writeGoroutine(0x5eb3a0, 0xc0000bc010, 0x2, 0x0, 0xc0000be6d0)
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/runtime/pprof/pprof.go:654 +0x4b
runtime/pprof.(*Profile).WriteTo(0x6f6d80, 0x5eb3a0, 0xc0000bc010, 0x2, 0x1, 0x10)
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/runtime/pprof/pprof.go:329 +0x3e1
github.com/safing/portbase/modules.init.3.func1()
	C:/Users/travis/gopath/src/github.com/safing/portbase/modules/tasks_test.go:20 +0xf5
created by github.com/safing/portbase/modules.init.3
	C:/Users/travis/gopath/src/github.com/safing/portbase/modules/tasks_test.go:17 +0x6c

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00015a7e0, 0x5b7ce1, 0x13, 0x5c2538, 0x48a201)
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/testing/testing.go:1043 +0x385
testing.runTests.func1(0xc00015a000)
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/testing/testing.go:1284 +0x7f
testing.tRunner(0xc00015a000, 0xc0000b9dd8)
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/testing/testing.go:991 +0xe3
testing.runTests(0xc00008b140, 0x6fae00, 0x8, 0x8, 0x0)
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/testing/testing.go:1282 +0x2ae
testing.(*M).Run(0xc0000ee280, 0x0)
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/testing/testing.go:1199 +0x166
main.main()
	_testmain.go:130 +0x1c8

goroutine 19 [select]:
github.com/safing/portbase/modules.microTaskScheduler()
	C:/Users/travis/gopath/src/github.com/safing/portbase/modules/microtasks.go:198 +0x2d5
created by github.com/safing/portbase/modules.init.2
	C:/Users/travis/gopath/src/github.com/safing/portbase/modules/microtasks_test.go:18 +0x3c

goroutine 20 [semacquire]:
sync.runtime_Semacquire(0x72dba8)
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0x72dba0)
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/sync/waitgroup.go:130 +0x6b
github.com/safing/portbase/modules.taskQueueHandler()
	C:/Users/travis/gopath/src/github.com/safing/portbase/modules/tasks.go:449 +0x8f
created by github.com/safing/portbase/modules.init.3
	C:/Users/travis/gopath/src/github.com/safing/portbase/modules/tasks_test.go:14 +0x3c

goroutine 21 [select]:
github.com/safing/portbase/modules.taskScheduleHandler()
	C:/Users/travis/gopath/src/github.com/safing/portbase/modules/tasks.go:489 +0x10d
created by github.com/safing/portbase/modules.init.3
	C:/Users/travis/gopath/src/github.com/safing/portbase/modules/tasks_test.go:15 +0x54

goroutine 23 [chan send]:
github.com/safing/portbase/modules.init.3.func2()
	C:/Users/travis/gopath/src/github.com/safing/portbase/modules/tasks_test.go:27 +0x3e
created by github.com/safing/portbase/modules.init.3
	C:/Users/travis/gopath/src/github.com/safing/portbase/modules/tasks_test.go:25 +0x84

goroutine 26 [chan receive]:
testing.(*T).Parallel(0xc00015a360)
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/testing/testing.go:867 +0x1dc
github.com/safing/portbase/modules.TestModules(0xc00015a360)
	C:/Users/travis/gopath/src/github.com/safing/portbase/modules/modules_test.go:49 +0x36
testing.tRunner(0xc00015a360, 0x5c2530)
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/testing/testing.go:991 +0xe3
created by testing.(*T).Run
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/testing/testing.go:1042 +0x35e

goroutine 32 [semacquire]:
sync.runtime_Semacquire(0xc000090d38)
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc000090d30)
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/sync/waitgroup.go:130 +0x6b
github.com/safing/portbase/modules.TestQueueSuccession(0xc00015a7e0)
	C:/Users/travis/gopath/src/github.com/safing/portbase/modules/tasks_test.go:250 +0xee
testing.tRunner(0xc00015a7e0, 0x5c2538)
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/testing/testing.go:991 +0xe3
created by testing.(*T).Run
	C:/Users/travis/.gimme/versions/go1.14.4.windows.amd64/src/testing/testing.go:1042 +0x35e

goroutine 12 [select]:
github.com/safing/portbase/modules.(*Task).runWithLocking.func1(0xc000048000)
	C:/Users/travis/gopath/src/github.com/safing/portbase/modules/tasks.go:313 +0xe5
created by github.com/safing/portbase/modules.(*Task).runWithLocking
	C:/Users/travis/gopath/src/github.com/safing/portbase/modules/tasks.go:312 +0x31e

FAIL	github.com/safing/portbase/modules	30.067s
FAIL
```

**Comment by dhaavi** [comment]
Possibly related recent fail on Linux:

```
===== FORCED EXIT =====
=== PRINTING TRACES ===
=== GOROUTINES ===
goroutine profile: total 49
7 @ 0x43a5d0 0x44a793 0x9bc92b 0x9bcf00 0x468981
#	0x9bc92a	github.com/safing/portbase/api.(*DatabaseAPI).processSub+0xda	/home/user/go/src/github.com/safing/portbase/api/database.go:370
#	0x9bceff	github.com/safing/portbase/api.(*DatabaseAPI).handleQsub+0x12f	/home/user/go/src/github.com/safing/portbase/api/database.go:434

6 @ 0x43a5d0 0x44b2d0 0x44b2bb 0x44af22 0x476164 0xa45f3b 0xa45127 0xa74255 0xa75fa0 0x53ec00 0x53e405 0xa7337a 0x776db4 0x776cfd 0x779420 0x779082 0x468981
#	0x44af21	sync.runtime_Semacquire+0x41								/usr/local/go/src/runtime/sema.go:56
#	0x476163	sync.(*WaitGroup).Wait+0x63								/usr/local/go/src/sync/waitgroup.go:130
#	0xa45f3a	github.com/safing/portmaster/resolver.deduplicateRequest+0x23a				/home/user/go/src/github.com/safing/portmaster/resolver/resolve.go:195
#	0xa45126	github.com/safing/portmaster/resolver.Resolve+0x246					/home/user/go/src/github.com/safing/portmaster/resolver/resolve.go:115
#	0xa74254	github.com/safing/portmaster/nameserver.handleRequest+0xe64				/home/user/go/src/github.com/safing/portmaster/nameserver/nameserver.go:261
#	0xa75f9f	github.com/safing/portmaster/nameserver.handleRequestAsWorker.func1+0x4f		/home/user/go/src/github.com/safing/portmaster/nameserver/nameserver.go:101
#	0x53ebff	github.com/safing/portbase/modules.(*Module).runWorker+0x9f				/home/user/go/src/github.com/safing/portbase/modules/worker.go:117
#	0x53e404	github.com/safing/portbase/modules.(*Module).RunWorker+0xb4				/home/user/go/src/github.com/safing/portbase/modules/worker.go:48
#	0xa73379	github.com/safing/portmaster/nameserver.handleRequestAsWorker+0x89			/home/user/go/src/github.com/safing/portmaster/nameserver/nameserver.go:100
#	0x776db3	github.com/safing/portmaster/vendor/github.com/miekg/dns.HandlerFunc.ServeDNS+0x43	/home/user/go/src/github.com/safing/portmaster/vendor/github.com/miekg/dns/server.go:37
#	0x776cfc	github.com/safing/portmaster/vendor/github.com/miekg/dns.(*ServeMux).ServeDNS+0x5c	/home/user/go/src/github.com/safing/portmaster/vendor/github.com/miekg/dns/serve_mux.go:103
#	0x77941f	github.com/safing/portmaster/vendor/github.com/miekg/dns.(*Server).serveDNS+0x2df	/home/user/go/src/github.com/safing/portmaster/vendor/github.com/miekg/dns/server.go:609
#	0x779081	github.com/safing/portmaster/vendor/github.com/miekg/dns.(*Server).serveUDPPacket+0xb1	/home/user/go/src/github.com/safing/portmaster/vendor/github.com/miekg/dns/server.go:549

4 @ 0x40689b 0xa63a41 0xa64ec9 0xa64f10 0x468981
#	0xa63a40	github.com/safing/portmaster/firewall/interception/nfqueue._Cfunc_loop_for_packets+0x40	_cgo_gotypes.go:124
#	0xa64ec8	github.com/safing/portmaster/firewall/interception/nfqueue.NewNFQueue.func1.1+0x58	/home/user/go/src/github.com/safing/portmaster/firewall/interception/nfqueue/nfqueue.go:63
#	0xa64f0f	github.com/safing/portmaster/firewall/interception/nfqueue.NewNFQueue.func1+0x2f	/home/user/go/src/github.com/safing/portmaster/firewall/interception/nfqueue/nfqueue.go:63

4 @ 0x43a5d0 0x40894d 0x408715 0xa4c2bd 0xa4c4f7 0xa463b4 0xa45076 0xa74255 0xa75fa0 0x53ec00 0x53e405 0xa7337a 0x776db4 0x776cfd 0x779420 0x779082 0x468981
#	0xa4c2bc	github.com/safing/portmaster/resolver.(*TCPResolver).submitQuery+0x23c			/home/user/go/src/github.com/safing/portmaster/resolver/resolver-tcp.go:113
#	0xa4c4f6	github.com/safing/portmaster/resolver.(*TCPResolver).Query+0x66				/home/user/go/src/github.com/safing/portmaster/resolver/resolver-tcp.go:142
#	0xa463b3	github.com/safing/portmaster/resolver.resolveAndCache+0x263				/home/user/go/src/github.com/safing/portmaster/resolver/resolve.go:253
#	0xa45075	github.com/safing/portmaster/resolver.Resolve+0x195					/home/user/go/src/github.com/safing/portmaster/resolver/resolve.go:132
#	0xa74254	github.com/safing/portmaster/nameserver.handleRequest+0xe64				/home/user/go/src/github.com/safing/portmaster/nameserver/nameserver.go:261
#	0xa75f9f	github.com/safing/portmaster/nameserver.handleRequestAsWorker.func1+0x4f		/home/user/go/src/github.com/safing/portmaster/nameserver/nameserver.go:101
#	0x53ebff	github.com/safing/portbase/modules.(*Module).runWorker+0x9f				/home/user/go/src/github.com/safing/portbase/modules/worker.go:117
#	0x53e404	github.com/safing/portbase/modules.(*Module).RunWorker+0xb4				/home/user/go/src/github.com/safing/portbase/modules/worker.go:48
#	0xa73379	github.com/safing/portmaster/nameserver.handleRequestAsWorker+0x89			/home/user/go/src/github.com/safing/portmaster/nameserver/nameserver.go:100
#	0x776db3	github.com/safing/portmaster/vendor/github.com/miekg/dns.HandlerFunc.ServeDNS+0x43	/home/user/go/src/github.com/safing/portmaster/vendor/github.com/miekg/dns/server.go:37
#	0x776cfc	github.com/safing/portmaster/vendor/github.com/miekg/dns.(*ServeMux).ServeDNS+0x5c	/home/user/go/src/github.com/safing/portmaster/vendor/github.com/miekg/dns/serve_mux.go:103
#	0x77941f	github.com/safing/portmaster/vendor/github.com/miekg/dns.(*Server).serveDNS+0x2df	/home/user/go/src/github.com/safing/portmaster/vendor/github.com/miekg/dns/server.go:609
#	0x779081	github.com/safing/portmaster/vendor/github.com/miekg/dns.(*Server).serveUDPPacket+0xb1	/home/user/go/src/github.com/safing/portmaster/vendor/github.com/miekg/dns/server.go:549

3 @ 0x43a5d0 0x40894d 0x408715 0xa4c2bd 0xa4c4f7 0xa463b4 0xa56aae 0x53ec00 0x53e405 0x5404b9 0x468981
#	0xa4c2bc	github.com/safing/portmaster/resolver.(*TCPResolver).submitQuery+0x23c	/home/user/go/src/github.com/safing/portmaster/resolver/resolver-tcp.go:113
#	0xa4c4f6	github.com/safing/portmaster/resolver.(*TCPResolver).Query+0x66		/home/user/go/src/github.com/safing/portmaster/resolver/resolver-tcp.go:142
#	0xa463b3	github.com/safing/portmaster/resolver.resolveAndCache+0x263		/home/user/go/src/github.com/safing/portmaster/resolver/resolve.go:253
#	0xa56aad	github.com/safing/portmaster/resolver.checkCache.func1+0x3d		/home/user/go/src/github.com/safing/portmaster/resolver/resolve.go:170
#	0x53ebff	github.com/safing/portbase/modules.(*Module).runWorker+0x9f		/home/user/go/src/github.com/safing/portbase/modules/worker.go:117
#	0x53e404	github.com/safing/portbase/modules.(*Module).RunWorker+0xb4		/home/user/go/src/github.com/safing/portbase/modules/worker.go:48
#	0x5404b8	github.com/safing/portbase/modules.(*Module).StartWorker.func1+0x58	/home/user/go/src/github.com/safing/portbase/modules/worker.go:27

3 @ 0x43a5d0 0x43355a 0x432ac5 0x498715 0x4995ab 0x49958d 0x60370f 0x6167de 0x4f8ce3 0x4f8e4f 0x9a2850 0x9a4dac 0x9a5e3f 0x9a65bf 0x9ba4a3 0x468981
#	0x432ac4	internal/poll.runtime_pollWait+0x54								/usr/local/go/src/runtime/netpoll.go:203
#	0x498714	internal/poll.(*pollDesc).wait+0x44								/usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#	0x4995aa	internal/poll.(*pollDesc).waitRead+0x19a							/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
#	0x49958c	internal/poll.(*FD).Read+0x17c									/usr/local/go/src/internal/poll/fd_unix.go:169
#	0x60370e	net.(*netFD).Read+0x4e										/usr/local/go/src/net/fd_unix.go:202
#	0x6167dd	net.(*conn).Read+0x8d										/usr/local/go/src/net/net.go:184
#	0x4f8ce2	bufio.(*Reader).fill+0x102									/usr/local/go/src/bufio/bufio.go:100
#	0x4f8e4e	bufio.(*Reader).Peek+0x4e									/usr/local/go/src/bufio/bufio.go:138
#	0x9a284f	github.com/safing/portbase/vendor/github.com/gorilla/websocket.(*Conn).read+0x3f		/home/user/go/src/github.com/safing/portbase/vendor/github.com/gorilla/websocket/conn.go:370
#	0x9a4dab	github.com/safing/portbase/vendor/github.com/gorilla/websocket.(*Conn).advanceFrame+0x5b	/home/user/go/src/github.com/safing/portbase/vendor/github.com/gorilla/websocket/conn.go:798
#	0x9a5e3e	github.com/safing/portbase/vendor/github.com/gorilla/websocket.(*Conn).NextReader+0x8e		/home/user/go/src/github.com/safing/portbase/vendor/github.com/gorilla/websocket/conn.go:980
#	0x9a65be	github.com/safing/portbase/vendor/github.com/gorilla/websocket.(*Conn).ReadMessage+0x2e		/home/user/go/src/github.com/safing/portbase/vendor/github.com/gorilla/websocket/conn.go:1064
#	0x9ba4a2	github.com/safing/portbase/api.(*DatabaseAPI).handler+0x42					/home/user/go/src/github.com/safing/portbase/api/database.go:126

3 @ 0x43a5d0 0x44a793 0x9bb0c3 0x468981
#	0x9bb0c2	github.com/safing/portbase/api.(*DatabaseAPI).writer+0xd2	/home/user/go/src/github.com/safing/portbase/api/database.go:197

2 @ 0x43a5d0 0x44a793 0x99c904 0x53ec00 0x53e731 0x468981
#	0x99c903	github.com/safing/portbase/rng.(*Feeder).run+0x2c3			/home/user/go/src/github.com/safing/portbase/rng/entropy.go:119
#	0x53ebff	github.com/safing/portbase/modules.(*Module).runWorker+0x9f		/home/user/go/src/github.com/safing/portbase/modules/worker.go:117
#	0x53e730	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x140	/home/user/go/src/github.com/safing/portbase/modules/worker.go:80

2 @ 0x43a5d0 0x44b2d0 0x44b2bb 0x44af22 0x476164 0x53feb3 0x468981
#	0x44af21	sync.runtime_Semacquire+0x41						/usr/local/go/src/runtime/sema.go:56
#	0x476163	sync.(*WaitGroup).Wait+0x63						/usr/local/go/src/sync/waitgroup.go:130
#	0x53feb2	github.com/safing/portbase/modules.(*Module).stopAllTasks.func2+0x32	/home/user/go/src/github.com/safing/portbase/modules/modules.go:247

1 @ 0x40e944 0x44f43c 0x501fb2 0x468981
#	0x44f43b	os/signal.signal_recv+0x9b	/usr/local/go/src/runtime/sigqueue.go:147
#	0x501fb1	os/signal.loop+0x21		/usr/local/go/src/os/signal/signal_unix.go:23

1 @ 0x43a5d0 0x409567 0x40922b 0x53b8ea 0x53b5a8 0x541696 0xa76347 0x43a1f2 0x468981
#	0x53b8e9	github.com/safing/portbase/modules.stopModules+0x1b9	/home/user/go/src/github.com/safing/portbase/modules/stop.go:92
#	0x53b5a7	github.com/safing/portbase/modules.Shutdown+0xc7	/home/user/go/src/github.com/safing/portbase/modules/stop.go:48
#	0x541695	github.com/safing/portbase/run.Run+0x345		/home/user/go/src/github.com/safing/portbase/run/main.go:104
#	0xa76346	main.main+0x96						/home/user/go/src/github.com/safing/portmaster/main.go:19
#	0x43a1f1	runtime.main+0x211					/usr/local/go/src/runtime/proc.go:203

1 @ 0x43a5d0 0x409567 0x40922b 0x86461b 0x468981
#	0x86461a	github.com/safing/portmaster/vendor/github.com/godbus/dbus.newConn.func1+0x4a	/home/user/go/src/github.com/safing/portmaster/vendor/github.com/godbus/dbus/conn.go:253

1 @ 0x43a5d0 0x43355a 0x432ac5 0x498715 0x499e4a 0x499e28 0x6039f0 0x628221 0x625ed8 0x86105d 0x476627 0x861808 0x8617c8 0x847e90 0x468981
#	0x432ac4	internal/poll.runtime_pollWait+0x54								/usr/local/go/src/runtime/netpoll.go:203
#	0x498714	internal/poll.(*pollDesc).wait+0x44								/usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#	0x499e49	internal/poll.(*pollDesc).waitRead+0x219							/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
#	0x499e27	internal/poll.(*FD).ReadMsg+0x1f7								/usr/local/go/src/internal/poll/fd_unix.go:243
#	0x6039ef	net.(*netFD).readMsg+0x8f									/usr/local/go/src/net/fd_unix.go:214
#	0x628220	net.(*UnixConn).readMsg+0x90									/usr/local/go/src/net/unixsock_posix.go:115
#	0x625ed7	net.(*UnixConn).ReadMsgUnix+0x97								/usr/local/go/src/net/unixsock.go:143
#	0x86105c	github.com/safing/portmaster/vendor/github.com/godbus/dbus.(*oobReader).Read+0x8c		/home/user/go/src/github.com/safing/portmaster/vendor/github.com/godbus/dbus/transport_unix.go:21
#	0x476626	io.ReadAtLeast+0x86										/usr/local/go/src/io/io.go:310
#	0x861807	io.ReadFull+0x117										/usr/local/go/src/io/io.go:329
#	0x8617c7	github.com/safing/portmaster/vendor/github.com/godbus/dbus.(*unixTransport).ReadMessage+0xd7	/home/user/go/src/github.com/safing/portmaster/vendor/github.com/godbus/dbus/transport_unix.go:91
#	0x847e8f	github.com/safing/portmaster/vendor/github.com/godbus/dbus.(*Conn).inWorker+0x3f		/home/user/go/src/github.com/safing/portmaster/vendor/github.com/godbus/dbus/conn.go:348

1 @ 0x43a5d0 0x44a793 0x531d5d 0x5318f9 0x468981
#	0x531d5c	github.com/safing/portbase/log.writer+0x40c		/home/user/go/src/github.com/safing/portbase/log/output.go:107
#	0x5318f8	github.com/safing/portbase/log.writerManager+0x98	/home/user/go/src/github.com/safing/portbase/log/output.go:54

1 @ 0x43a5d0 0x44a793 0x538eca 0x468981
#	0x538ec9	github.com/safing/portbase/modules.(*Module).stopAllTasks+0x159	/home/user/go/src/github.com/safing/portbase/modules/modules.go:252

1 @ 0x43a5d0 0x44a793 0x7781fc 0xa7314a 0xa73155 0x53ef12 0x53fe0d 0x468981
#	0x7781fb	github.com/safing/portmaster/vendor/github.com/miekg/dns.(*Server).ShutdownContext+0x1eb	/home/user/go/src/github.com/safing/portmaster/vendor/github.com/miekg/dns/server.go:381
#	0xa73149	github.com/safing/portmaster/vendor/github.com/miekg/dns.(*Server).Shutdown+0x49		/home/user/go/src/github.com/safing/portmaster/vendor/github.com/miekg/dns/server.go:345
#	0xa73154	github.com/safing/portmaster/nameserver.stop+0x54						/home/user/go/src/github.com/safing/portmaster/nameserver/nameserver.go:88
#	0x53ef11	github.com/safing/portbase/modules.(*Module).runCtrlFn+0x91					/home/user/go/src/github.com/safing/portbase/modules/worker.go:153
#	0x53fe0c	github.com/safing/portbase/modules.(*Module).stopAllTasks.func1+0x4c				/home/user/go/src/github.com/safing/portbase/modules/modules.go:238

1 @ 0x43a5d0 0x44a793 0x91b373 0x53ec00 0x53e731 0x468981
#	0x91b372	github.com/safing/portmaster/netenv.monitorNetworkChanges+0x152		/home/user/go/src/github.com/safing/portmaster/netenv/network-change.go:37
#	0x53ebff	github.com/safing/portbase/modules.(*Module).runWorker+0x9f		/home/user/go/src/github.com/safing/portbase/modules/worker.go:117
#	0x53e730	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x140	/home/user/go/src/github.com/safing/portbase/modules/worker.go:80

1 @ 0x43a5d0 0x44a793 0x91c8c7 0x53ec00 0x53e731 0x468981
#	0x91c8c6	github.com/safing/portmaster/netenv.monitorOnlineStatus+0x136		/home/user/go/src/github.com/safing/portmaster/netenv/online-status.go:273
#	0x53ebff	github.com/safing/portbase/modules.(*Module).runWorker+0x9f		/home/user/go/src/github.com/safing/portbase/modules/worker.go:117
#	0x53e730	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x140	/home/user/go/src/github.com/safing/portbase/modules/worker.go:80

1 @ 0x43a5d0 0x44a793 0x99cc14 0x53ec00 0x53e731 0x468981
#	0x99cc13	github.com/safing/portbase/rng.fullFeeder+0x153				/home/user/go/src/github.com/safing/portbase/rng/fullfeed.go:25
#	0x53ebff	github.com/safing/portbase/modules.(*Module).runWorker+0x9f		/home/user/go/src/github.com/safing/portbase/modules/worker.go:117
#	0x53e730	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x140	/home/user/go/src/github.com/safing/portbase/modules/worker.go:80

1 @ 0x43a5d0 0x44a793 0x99d617 0x53ec00 0x53e731 0x468981
#	0x99d616	github.com/safing/portbase/rng.osFeeder+0x1d6				/home/user/go/src/github.com/safing/portbase/rng/osfeeder.go:27
#	0x53ebff	github.com/safing/portbase/modules.(*Module).runWorker+0x9f		/home/user/go/src/github.com/safing/portbase/modules/worker.go:117
#	0x53e730	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x140	/home/user/go/src/github.com/safing/portbase/modules/worker.go:80

1 @ 0x43a5d0 0x44a793 0x99def3 0x53ec00 0x53e731 0x468981
#	0x99def2	github.com/safing/portbase/rng.tickFeeder+0x242				/home/user/go/src/github.com/safing/portbase/rng/tickfeeder.go:60
#	0x53ebff	github.com/safing/portbase/modules.(*Module).runWorker+0x9f		/home/user/go/src/github.com/safing/portbase/modules/worker.go:117
#	0x53e730	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x140	/home/user/go/src/github.com/safing/portbase/modules/worker.go:80

1 @ 0x43a5d0 0x44b2d0 0x44b2bb 0x44af22 0x476164 0x7ad40b 0x778b03 0x77772c 0xa75ec1 0x53ec00 0x53e731 0x468981
#	0x44af21	sync.runtime_Semacquire+0x41								/usr/local/go/src/runtime/sema.go:56
#	0x476163	sync.(*WaitGroup).Wait+0x63								/usr/local/go/src/sync/waitgroup.go:130
#	0x7ad40a	github.com/safing/portmaster/vendor/github.com/miekg/dns.(*Server).serveUDP.func1+0x2a	/home/user/go/src/github.com/safing/portmaster/vendor/github.com/miekg/dns/server.go:455
#	0x778b02	github.com/safing/portmaster/vendor/github.com/miekg/dns.(*Server).serveUDP+0x3b2	/home/user/go/src/github.com/safing/portmaster/vendor/github.com/miekg/dns/server.go:465
#	0x77772b	github.com/safing/portmaster/vendor/github.com/miekg/dns.(*Server).ListenAndServe+0x36b	/home/user/go/src/github.com/safing/portmaster/vendor/github.com/miekg/dns/server.go:302
#	0xa75ec0	github.com/safing/portmaster/nameserver.start.func1+0x30				/home/user/go/src/github.com/safing/portmaster/nameserver/nameserver.go:68
#	0x53ebff	github.com/safing/portbase/modules.(*Module).runWorker+0x9f				/home/user/go/src/github.com/safing/portbase/modules/worker.go:117
#	0x53e730	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x140			/home/user/go/src/github.com/safing/portbase/modules/worker.go:80

1 @ 0x43a5d0 0x45773a 0x541ed4 0x468981
#	0x457739	time.Sleep+0xb9					/usr/local/go/src/runtime/time.go:188
#	0x541ed3	github.com/safing/portbase/run.Run.func2+0x33	/home/user/go/src/github.com/safing/portbase/run/main.go:98

1 @ 0x526c05 0x526a20 0x5237ba 0x541b9d 0x541e7e 0x468981
#	0x526c04	runtime/pprof.writeRuntimeProfile+0x94			/usr/local/go/src/runtime/pprof/pprof.go:694
#	0x526a1f	runtime/pprof.writeGoroutine+0x9f			/usr/local/go/src/runtime/pprof/pprof.go:656
#	0x5237b9	runtime/pprof.(*Profile).WriteTo+0x3d9			/usr/local/go/src/runtime/pprof/pprof.go:329
#	0x541b9c	github.com/safing/portbase/run.printStackTo+0x10c	/home/user/go/src/github.com/safing/portbase/run/main.go:137
#	0x541e7d	github.com/safing/portbase/run.Run.func1+0x13d		/home/user/go/src/github.com/safing/portbase/run/main.go:87

=== BLOCKING ===
--- contention:
cycles/second=2304074219
=== MUTEXES ===
--- mutex:
cycles/second=2304074219
sampling period=0
=== END TRACES ===
```
